# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abd63510674b5ec58a01678a1a6c21c79a8a6fdc7978c7322a438415371e418dd5d24d121c7c314c420df39ab17b8b117e6626727db5b87f168d21b4451bf379

test:
  secret_key_base: cbe1039f950874e6ecf092f6cd5df1f3dde678990c0e3af3d7b217773208542a85bc4680514db333c8c3273dd7a3a7fabf2c4e7e5a0ad5f92ed12f15b2891476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
